### ISSUE TITLE
Improve StripedExecutorService performance.

### ISSUE THREAD

**Issue by sbernard31** [kabutz/javaspecialists#1]
Hi,
  I'm committer on [Californium project][1], a CoAP java implementation.
  In this project we also develop a DTLS layer named [Scandium][2] in which we use your StripedExecutorService.

  Facing some CPU issue, I played with visualVM and see that scheduleNext() method is regularly mentioned in the hot-spot.
  I don't think this is the real responsible of my CPU issue, but I was surprised to see this method seems to use more CPU than cryptographic stuff. I suspect the issue is the lock style implementation (mainly in SerialExecutor).

  I read that [you tried to enhance that][3], Did you succeed ?
  We would like to improve this, do you have any advices or clues about the way to follow ?
Thx

[1]: https://github.com/eclipse/californium/tree/2.0.x
[2]: https://github.com/eclipse/californium/tree/2.0.x/scandium-core
[3]: http://cs.oswego.edu/pipermail/concurrency-interest/2012-November/010199.html
[4]: http://jsr166-concurrency.10961.n7.nabble.com/Class-striped-ordered-Thread-Pool-td8777i20.html#a8788

**Comment by kabutz** [comment]
Hi Simon, thanks for your interest.  I think one needs to get away completely from the baggage of the ThreadPoolExecutor and re-engineer this from scratch.  I did not get much response to my email in 2012 and so left it in my "todo" box for when I have time.  I'm happy to work on this together if you're interested?

**Comment by sbernard31** [comment]
I'm clearly interested. Could you be more precise about what you have in mind ?

**Comment by sbernard31** [comment]
@kabutz ping (just in case you missed my last message)

**Comment by kabutz** [comment]
"The irony, jmh bench results sounds to show a kind of improvement but I can not see any significant impact in the application in which we are using StripedExecutor. (meaning that I maybe aim the wrong target or there is others bottleneck)" - this is precisely what I was expecting.  Considering that the payload of your tasks is probably many factors higher than the scheduling cost, I was always doubtful that this would be something to aim at.

The purpose of the StripedExecutorService was to execute classes of tasks in-order.  The design should probably have one queue per task and threads picking off these tasks in a round-robin fashion.  However, if that isn't the bottleneck in the system, why bother?

**Comment by sbernard31** [comment]
It's a bit more complicated.
Actually, https://github.com/eclipse/californium/issues/559 seems to show `StripedExecutorService` impacts performance.

But replacing it with my version seems not to improve it.

> However, if that isn't the bottleneck in the system, why bother?

To be honest, I spend a lot of time to analyze/profiling the application and I'm clearly more and more confuse about what impacts performance.

I suppose that the reasonable thing to do is to let this beside for now. (even if this really hard to me to stop on a kind of failure)

Just by curiosity, did you have a look at my StripedExecutorService ? I would like to know if the spirit is totally wrong or if it's ok ?

Anyway, if you works again on this later, please let me now. I'm curious about it.
