### ISSUE TITLE
Code and Config for Newsletter 285

### ISSUE THREAD

**Issue by DeanJain** [kabutz/javaspecialists#3]
Hello @kabutz, do you mind sharing code and config for below interesting test ?

https://www.javaspecialists.eu/archive/Issue285-I-O-Stream-Memory-Overhead.html

**Comment by kabutz** [comment]
It took a bit of linux config to get it right. That was harder than the Java part. On the server it was basically just the code you saw and a loop calling accept() on the ServerSocket and then starting a virtual thread. The client was a bit more complex, as we didn't want to swamp the server and also didn't want to overrun the carrier thread pool with too many requests all at once.
